### ISSUE TITLE
Feedback from team 15

### ISSUE THREAD

**Issue by Moyne** [Mattia9918/HikeTracker#11]
*As an hiker I really like the interface and the fact that also a visitor sees an image for a hike, but I think the filtering part is a little tedious, especially for the area selection.*

***

*As a platform manager I like the idea of having a username tied to an account and not just an email but I don't agree with the user capability to choose its type immediately at registration time because it's less efficient for managing more important roles like a local guide.*

***Good job!***

**Comment by Mattia9918** [comment]
Thank'you for your feedback:

1) The filtering part has been simplified, and now is much more intuitive and requires much less effort from the user: filtering via forms has been replaced by interfacing via react-bootstrap accordion component.

2) For what regards the registration, only hikers can register directly via registration form. Only momentarily, before the development of the appropriate story, the platform manager and local guide accounts will be hardcoded into the database.
