### ISSUE TITLE
Marker improvement

### ISSUE THREAD

**Issue by SofiaBelloni** [Mattia9918/HikeTracker#16]
The map showing the hike's track has a very nice design but I recommend marking in a different way the starting point, arrival point and intermediate points to allow the hiker to better understand the hike.

**Comment by FrancescoSantoro7** [comment]
Maybe you can just select different colors to mark the parking lots/huts and start/end points of the hike

**Comment by Mattia9918** [comment]
Thank you for your feedback, 

the map marker icons have been modified according to your suggestions: now it's immediately understandable which are starting points, ending points and intermediate ones.
